spring:
  application:
    name: solen
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss,SSS
    time-zone: Asia/Shanghai
solen:
  server:
    port: 7889

logging:
  level:
    top.fengpingtech.solen: debug
    io.netty: debug