spring:
  application:
    name: solen
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss,SSS
    time-zone: Asia/Shanghai
  datasource:
    url: jdbc:hsqldb:file:data/solen-data
    username: sa
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  sql:
    init:
      mode: always
      schema-locations: [ classpath:schema.sql, classpath:data.sql ]

solen:
  server:
    port: 7889
  auth:
    tenants:
      - app-key: test
        secret-key: test
        pass-key: test
        roles: [ USER ]
        device-patterns: [ "555**", "400**" ]
      - app-key: admin
        secret-key: 123asdsecret123asdfadmin
        pass-key: admin
        roles: [ ADMIN ]
        device-patterns: ["**"]
    jwt:
      secret: d41d8cd98f00b204e9800998ecf8427e
      ttl: 3600000
      issuer: http://iot-online.fengping-tech.top

logging:
  level:
    top.fengpingtech.solen: debug
    io.netty: debug
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}]"